[tool.pytest.ini_options]
addopts=''# добавление аргументов ко всем тестам проекта
markers=[
    'fast: маркируем тесты длящиеся меньше 5 секунд',
    'slow: маркируем тесты длящиеся больше 5 секунд'
]